#!/bin/bash

RESTRICT_REPOSITORY="dials/data"
if [[ "${TRAVIS_REPO_SLUG}" != "${RESTRICT_REPOSITORY}" ]]; then
  echo Skipping step outside of ${RESTRICT_REPOSITORY} repository
  exit 0
fi

if [[ "${TRAVIS_BUILD_NUMBER}.1" != "${TRAVIS_JOB_NUMBER}" ]]; then
  echo Skipping step in jobs other than .1
  exit 0
fi

git config --global user.name "Automated commit via Travis CI"
git config --global user.email "DiamondLightSource-build-server@users.noreply.github.com"
git config credential.helper "store --file=.git/credentials"
echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials

if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  echo Installing github cli
  pushd .. >/dev/null
  wget -nv https://github.com/github/hub/releases/download/v2.6.0/hub-linux-amd64-2.6.0.tgz -O - | tar xz || exit 1
  export PATH=$(pwd)/hub-linux-amd64-2.6.0/bin/:${PATH}
  popd >/dev/null
  hub --version || exit 1

  echo Open pull requests:
  declare -A UPDATEBRANCHES
  for BRANCH in $(hub pr list -b master -f '%H%n'); do
    echo ${BRANCH}
    UPDATEBRANCHES[${BRANCH}]=1
  done
  echo

  echo Installing package outside tox environment
  pip install -e .

  echo Checking for required definition updates...
  for DATASET in $(python -c "import dials_data.datasets as ddd; print('\n'.join(ddd.fileinfo_dirty))")
  do
    echo Checking ${DATASET}
    [ ${UPDATEBRANCHES[update-${DATASET}]+x} ] || {
      echo create/update branch ${DATASET}
      git checkout -b "update-${DATASET}"
      git reset --hard master
      git commit --allow-empty -m "Trigger update of dataset ${DATASET}"
      git push -f -u origin "update-${DATASET}"
      echo create pull request
      hub pull-request -f -m "Update dataset ${DATASET}"
    }
  done
fi

if [[ ${TRAVIS_BRANCH} == update-* ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  CANDIDATE=$(echo ${TRAVIS_BRANCH} | cut -c 8-)
  if [[ ! -z $CANDIDATE ]]; then
    echo Installing package outside tox environment
    pip install -e .

    echo Considering updating information on dataset ${CANDIDATE}
    for DATASET in $(python -c "import dials_data.datasets as ddd; print('\n'.join(ddd.fileinfo_dirty))")
    do
      if [[ "${DATASET}" == "${CANDIDATE}" ]]; then
        echo Updating dataset ${DATASET}
      fi
    done
  fi
fi
