#!/bin/bash

VERSION=$(grep version dials_data/__init__.py | cut -d'"' -f 2)
BASETAG=v${VERSION}
DEPTH=$(git rev-list ${BASETAG}..HEAD --count)
REAL_VERSION=${VERSION%.0}.${DEPTH}
sed -i "s/^__version__.*/__version__ = \"${REAL_VERSION}\"/" dials_data/__init__.py
sed -i "s/^\(\s\+\)version=\".*\",$/\1version=\"${REAL_VERSION}\",/" setup.py
echo Set package version from ${VERSION} to ${REAL_VERSION}
